version: "3"

services:
  server:
    build: ./server
    expose:
      - 3000
    environment:
      API_HOST: "http://localhost3000/"
      APP_SERVER_PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./server.src:/srv/app/client
    command: npm  start

  client:
    build: .
    environment:
      REACT_HOST: "http://everythingcalgary.me/"
      REACT_APP_PORT: 8080
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - ./client/src:/srv/app/client
      - ./client/public:/srv/app/client
    links:
      - server
    command: npm start
